### PR TITLE
Add renderer component for itk-viewer-2d custom element

### PR DESCRIPTION
**Pull request by PaulHax**
Just a stab at what the itk-viewer renderer plugin would look like.  Based the `viewer.tsx` and `viewer.client.tsx` on this working test getting itk-viewer going in a Remix CRA base project.  https://github.com/PaulHax/remix-itk-viewer-example/commit/bfc0f41e82da44e0134190329e942a171891c3b2

related to #1

### CODE REVIEW

**Comment by PaulHax** [comment]
@stevejpurves I think all that is left TODO is 

- [ ] Wire renderer plugin into theme build
- [ ] Ask server to staticly serve some Web Assembly assest under `plipelines` https://github.com/PaulHax/remix-itk-viewer-example/commit/bfc0f41e82da44e0134190329e942a171891c3b2#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddR17-R29

**Comment by stevejpurves** [comment]
@PaulHax thanks for the ping! let me try and take this over the line, will be able to get some time on it tomorrow

**Comment by PaulHax** [comment]
Heyo @stevejpurves Is there anything I can do to help out here.  (I know this viewer of ours has a few integration rough edges...)

**Comment by stevejpurves** [comment]
@PaulHax sorry i got swamped - Are you at scipy? maybe we could hack on this there?

**Comment by thewtex** [comment]
Hi @stevejpurves, I am traveling to SciPy tomorrow; we would love to work with you on this. We might be able to bring in Paul remotely.

**Pull request merged**
